name: Publish Package

on:
  push:
    tags:
      - "release-*"
  workflow_dispatch:
    # allow manual trigger

jobs:
  build:
    permissions:
      contents: write
      packages: write
    uses: ExtractIntoVoid/workflows/.github/workflows/package.yml@main
    with:
      ProjName: RENAME_ME
#      runner: windows-latest
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}