name: Build Solution

on:
  workflow_call:
    inputs:
        runner:
            required: false
            type: string
            default: windows-latest
        uploadName:
            required: false
            type: string
            default: Output
        config:
            required: false
            type: string
            default: Release
    secrets:
        TOKEN:
            required: true

jobs:
    build:
        name: Build
        runs-on: ${{ inputs.runner }}
        permissions:
            contents: read
            packages: read

        steps:
            - uses: actions/checkout@v5

            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                dotnet-version: 10.0.x

            - name: Add GitHub NuGet Source
              run: dotnet nuget add source https://nuget.pkg.github.com/ExtractIntoVoid/index.json --name "github" --username "Workflow" --password ${{ secrets.TOKEN }} --store-password-in-clear-text

            - name: Build
              run: dotnet build -p:BaseOutputPath="../Out/" -c:${{ inputs.config }}

            - name: Run test
              run: dotnet test

            - name : Upload
              uses: actions/upload-artifact@v5
              with:
                name: ${{ inputs.uploadName }}
                path: Out/*