name: Build Project

on:
  workflow_call:
    inputs:
        ProjName:
          required: true
          type: string
        runner:
            required: false
            type: string
            default: windows-latest
        uploadName:
            required: false
            type: string
        config:
            required: false
            type: string
            default: Release
    secrets:
        TOKEN:
            required: true

jobs:
    build:
        name: Build
        runs-on: ${{ inputs.runner }}
        permissions:
            contents: read
            packages: read

        steps:
            - uses: actions/checkout@v6

            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                dotnet-version: 10.0.x

            - name: Add GitHub NuGet Source
              run: dotnet nuget add source https://nuget.pkg.github.com/ExtractIntoVoid/index.json --name "github" --username "Workflow" --password ${{ secrets.TOKEN }} --store-password-in-clear-text

            - name: Build
              run: dotnet build ${{ inputs.ProjName }}/${{ inputs.ProjName }}.csproj -c:${{ inputs.config }} -o Out

            - name: Run test
              run: dotnet test

            - name : Upload
              uses: actions/upload-artifact@v7
              with:
                name: ${{ inputs.uploadName || inputs.ProjName }}
                path: Out/*
